### ISSUE TITLE
致谢

### ISSUE THREAD

**Issue by goleillie** [fangvv/PdfAutoRenameTools#2]
工作需要经常需要下载pdf文件，您的工具让我受益良多，有些建议：
在处理国家标准和有封面的报告之类通常无效，这类文件通常标题是首页字号最大的部分，如果能增加这样的处理规则就好了

**Comment by fangvv** [comment]
这是根据原作者的工作修改的，代码中可以看到，其实就是提取了前几行做比对。至于说国家标准和封面报告，这个格式会有非常非常大的差异，会非常的五花八门，可能需要自己根据需要来进行调试。
